In [1]:
# Import dependencies
from splinter import Browser
from bs4 import BeautifulSoup as soup
import pandas as pd
from webdriver_manager.chrome import ChromeDriverManager
import requests
import lxml.html as lh

In [2]:
# Potential boilerplate code for web scraping
# Set the executable path and initialize Splinter
executable_path = {'executable_path': ChromeDriverManager().install()}
browser = Browser('chrome', **executable_path, headless=False)

====== WebDriver manager ======
Current google-chrome version is 99.0.4844
Get LATEST chromedriver version for 99.0.4844 google-chrome
Driver [/Users/michaelbinger/.wdm/drivers/chromedriver/mac64/99.0.4844.51/chromedriver] found in cache

In [3]:
# URL for baseball reference as a starting point
# url = 'https://www.baseball-reference.com/leagues/majors/2021-standard-batting.shtml'
# browser.visit(url)
# Consider writing code to pull current date, extract year, and apply it to URL. Would have to subtract year by 1

In [4]:
# Convert the browser html to a soup object and then quit the browser
# html = browser.html
# news_soup = soup(html, 'html.parser')

In [5]:
# stats_table = news_soup.select_one('div_players_standard_batting')
# print(stats_table)

In [6]:
# Navigate to table in baseball reference, either pull whole table or create a dataframe by looping through it's values

In [7]:
######################################################################################
######################################################################################
###    TRY THIS POKEMON EXAMPLE FROM ONLINE
###    https://towardsdatascience.com/web-scraping-html-tables-with-python-c9baba21059
######################################################################################
######################################################################################

In [9]:
url='https://www.baseball-reference.com/leagues/majors/2021-standard-batting.shtml'
#Create a handle, page, to handle the contents of the website
page = requests.get(url)
#Store the contents of the website under doc
doc = lh.fromstring(page.content)
#Parse data that are stored between <tr>..</tr> of HTML
tr_elements = doc.xpath('//tr')

In [12]:
#Check the length of the first 12 rows
[len(T) for T in tr_elements[:12]]

[29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29]

In [14]:
tr_elements = doc.xpath('//tr')
#Create empty list
col=[]
i=0
#For each row, store each first element (header) and an empty list
for t in tr_elements[0]:
    i+=1
    name=t.text_content()
    col.append((name,[]))

col

[('Tm', []),
 ('#Bat', []),
 ('BatAge', []),
 ('R/G', []),
 ('G', []),
 ('PA', []),
 ('AB', []),
 ('R', []),
 ('H', []),
 ('2B', []),
 ('3B', []),
 ('HR', []),
 ('RBI', []),
 ('SB', []),
 ('CS', []),
 ('BB', []),
 ('SO', []),
 ('BA', []),
 ('OBP', []),
 ('SLG', []),
 ('OPS', []),
 ('OPS+', []),
 ('TB', []),
 ('GDP', []),
 ('HBP', []),
 ('SH', []),
 ('SF', []),
 ('IBB', []),
 ('LOB', [])]

In [15]:
#Since our first row is the header, data is stored on the second row onwards
for j in range(1,len(tr_elements)):
    
    #T is our j'th row
    T=tr_elements[j]
    
    #If row is not of size 10, the //tr data is not from our table 
    if len(T)!=29:
        break
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        #Check if row is empty
        if i>0:
        #Convert any numerical value to integers
            try:
                data=int(data)
            except:
                pass
        #Append the data to the empty list of the i'th column
        col[i][1].append(data)
        #Increment i for the next column
        i+=1

In [16]:
[len(C) for (title,C) in col]

[33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33,
 33]

In [17]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [19]:
df

,Tm,#Bat,BatAge,R/G,G,PA,AB,R,H,2B,...,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB
0,Arizona Diamondbacks,64,28.9,4.19,162,6144,5489,679,1297,308,...,.382,.692,87,2099,99,54,32,28,24,1131
1,Atlanta Braves,56,28.2,4.91,161,6056,5363,790,1307,269,...,.435,.754,96,2333,81,67,32,43,36,1054
2,Baltimore Orioles,62,26.7,4.07,162,5983,5420,659,1296,266,...,.402,.705,90,2177,105,65,14,31,12,1033
3,Boston Red Sox,56,28.0,5.12,162,6122,5495,829,1434,330,...,.449,.777,104,2467,100,61,10,42,22,1071
4,Chicago Cubs,69,29.1,4.35,162,5972,5306,705,1255,225,...,.407,.719,93,2162,133,92,40,30,17,1001
5,Chicago White Sox,47,28.0,4.91,162,6084,5357,796,1373,275,...,.422,.758,107,2262,139,78,24,39,10,1111
6,Cincinnati Reds,55,28.9,4.85,162,6162,5423,786,1352,295,...,.431,.759,93,2339,129,105,35,45,22,1085
7,Cleveland Indians,48,26.7,4.43,162,5907,5332,717,1269,248,...,.407,.710,93,2170,105,64,20,36,18,969
8,Colorado Rockies,45,28.1,4.59,161,6007,5374,739,1338,275,...,.414,.731,87,2227,98,58,48,36,24,1050
9,Detroit Tigers,49,28.1,4.30,162,5979,5376,697,1299,236,...,.399,.707,97,2146,113,44,17,50,8,1006
10,Houston Astros,52,28.9,5.33,162,6291,5593,863,1496,299,...,.444,.783,113,2486,136,64,9,54,25,1134
11,Kansas City Royals,48,29.3,4.23,162,5993,5427,686,1349,251,...,.396,.702,88,2147,100,55,31,52,8,1036
12,Los Angeles Angels,64,29.2,4.46,162,6016,5437,723,1331,265,...,.407,.717,94,2212,107,59,30,25,35,1015
13,Los Angeles Dodgers,61,29.2,5.12,162,6239,5445,830,1330,247,...,.429,.759,103,2336,96,104,32,45,36,1139
14,Miami Marlins,61,28.2,3.85,162,5929,5348,623,1244,226,...,.372,.671,82,1990,95,65,30,30,25,1020
15,Milwaukee Brewers,61,28.7,4.56,162,6099,5362,738,1251,255,...,.396,.713,91,2124,102,88,25,35,26,1088
16,Minnesota Twins,57,28.3,4.50,162,6078,5431,729,1311,271,...,.423,.738,103,2300,122,70,7,42,17,1063
17,New York Mets,64,28.2,3.93,162,5856,5210,636,1243,228,...,.391,.705,94,2035,123,94,34,23,25,1073
18,New York Yankees,59,29.3,4.39,162,6060,5331,711,1266,213,...,.407,.729,100,2169,154,63,10,34,14,1073
19,Oakland Athletics,50,30.1,4.59,162,6104,5395,743,1284,271,...,.406,.723,102,2190,99,98,17,49,17,1069
20,Philadelphia Phillies,55,29.1,4.53,162,6089,5366,734,1288,262,...,.408,.726,95,2192,103,67,47,43,37,1095
21,Pittsburgh Pirates,64,27.5,3.76,162,5983,5336,609,1261,240,...,.364,.673,83,1943,102,49,31,37,24,1116
22,San Diego Padres,54,28.0,4.50,162,6119,5384,729,1305,273,...,.401,.722,101,2160,121,61,36,46,42,1095
23,Seattle Mariners,63,27.0,4.30,162,6010,5355,697,1209,233,...,.385,.688,92,2061,92,72,9,36,8,1012
24,San Francisco Giants,54,30.6,4.96,162,6196,5462,804,1360,271,...,.440,.769,107,2404,117,64,36,30,45,1109
25,St. Louis Cardinals,51,28.5,4.36,162,6001,5351,706,1303,261,...,.412,.725,101,2202,99,86,40,44,32,1070
26,Tampa Bay Rays,61,27.7,5.29,162,6213,5507,857,1336,288,...,.429,.750,112,2362,75,72,6,41,27,1056
27,Texas Rangers,54,26.8,3.86,162,5943,5405,625,1254,225,...,.375,.670,84,2028,113,58,16,31,10,982
28,Toronto Blue Jays,62,26.8,5.22,162,6070,5476,846,1455,285,...,.466,.797,115,2552,112,51,10,35,14,1039
29,Washington Nationals,60,28.7,4.47,162,6113,5385,724,1388,272,...,.417,.754,107,2246,158,84,38,31,43,1168
30,League Average,50,28.4,4.53,162,6061,5398,734,1316,262,...,.411,.728,97,2217,111,70,26,38,23,1065
31,,1508,28.4,4.53,4858,181818,161941,22010,39484,7863,...,.411,.728,97,66521,3328,2112,766,1143,703,31963
32,Tm,#Bat,BatAge,R/G,G,PA,AB,R,H,2B,...,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB

In [20]:
tables = soup.find_all("table")  # returns a list of tables
second_table = tables[1]

AttributeError: 'str' object has no attribute 'descendants'